### ISSUE TITLE
MainServer's listing of periodic events

### ISSUE THREAD

**Issue by Light-Of-Darkness** [SYSC-3010-F5/AVA-SH#25]
The MainServer will list the periodic event multiple times, as if they were each separate events.
It will also list the same trigger day for each event.

As an example, the following was displayed after the server received a command to schedule a ping every week on Saturdays and Mondays at 3:35
![image](https://cloud.githubusercontent.com/assets/22303564/24075531/aae222ea-0bf3-11e7-87d8-f8e9f00f1e5d.png)

**Comment by JasonVanKerkhoven** [comment]
Is this only a print error, or is it from the server scheduling it too many times?

**Comment by JasonVanKerkhoven** [comment]
@Light-Of-Darkness 
Also is that shown in the main DKSY output, or the little side panel showing active events?

**Comment by Light-Of-Darkness** [comment]
It seems to only be a print error

**Comment by Light-Of-Darkness** [comment]
Only in the side view if the main DSKY

**Comment by JasonVanKerkhoven** [comment]
After removing the periodic event, the DSKY still shows that it is scheduled.
![image](https://cloud.githubusercontent.com/assets/22297889/24468884/ae88e40a-1487-11e7-8dc3-3c1891bead67.png)
> _Figure 1 -- shows that after periodic event "Test Alarm" is removed, it still remains in the printout on the DKSY, event after manual DSKY update via "Update Events" button_

**Comment by JasonVanKerkhoven** [comment]
Closing this issue, as the problem **is not** just a printing issue.
The conclusions in this issue are under the false assumption it is only a printing error
There is a larger problem with the scheduling, logged as issue #36
