### ISSUE TITLE
alarmClock.py TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by NVRC** [SYSC-3010-F5/AVA-SH#26]
`alarmClock.py`, when ran in Python 2.7.8, provokes the language to thrown `ImportError: No module named pygame` as I suppose it is not a supported feature. Additionally, when run in Python 3.4.5, `TabError: inconsistent use of tabs and spaces in indentation` is thrown. If specific libraries or Python versions are required, a brief `ReadMe` could be useful.

Python savants, do your **magic!**

**Comment by JasonVanKerkhoven** [comment]
The tab characters are all saved in the files as spaces. That could be why python doesn't like the indentation (if its looking for tabs not spaces)

**Comment by NVRC** [comment]
Right, you did mention that on Slack. At worst we'll have to manually modify it. I'm curious to know which IDEs do that.

**Comment by sarahgarlough** [comment]
I'm not having any issues running off of the pi, and its taken right from pythons IDLE. I believe the pi is running 2.5.3, but I will double check tomorrow.
