### ISSUE TITLE
Periodic Event Scheduling

### ISSUE THREAD

**Issue by JasonVanKerkhoven** [SYSC-3010-F5/AVA-SH#36]
Each periodic event scheduled is actually being added the `Scheduler`'s list of periodic events *7* times. It is always added 7 times, regardless of the days it triggers on.

It is unknown whether the events are:

1. Properly being  scheduled 7 times (ie 7 instances of the same event are added to the `Scheduler.Timer` instance, which in turn means the event will run 7 daemon threads and trigger 7 times per trigger)
2. If the event is only being added the the `Scheduler.ArrayList` used to "keep a master list" of all scheduled events.

After some (really quick) testing it looks like it is probably the later of the two

Citing issue #25 , it is not **just** a printout error.
There is actually an error in the periodic scheduling method,

**Comment by JasonVanKerkhoven** [comment]
Scheduling a periodic event that occurs _daily_ is fine
The bug only occurs when scheduling a periodic event that _doesn't_ occur everyday per week

Commands use to replicate this are
> alarm-new mon,tue,wed,thu,fri,sat,sun 6:08
> alarm-new sun,tue,thu,sat 16:21 "Every 2nd Day"
> npe-get

Result in the following printout

![image](https://cloud.githubusercontent.com/assets/22297889/24516213/dcccaa2a-1547-11e7-92e2-6bb6ee795557.png)
> _figure -- shows the event scheduled everyday is added correctly, where the event scheduled to trigger every other day (sun, tues, thurs, sat) is incorrectly scheduled 7 times_

**Comment by JasonVanKerkhoven** [comment]
Periodic event scheduling also allows multiple periodic events under the same name to be scheduled, ie two periodic events under name "Alaram1" can be entered. This should result in an error

**Comment by Light-Of-Darkness** [comment]
In the loop that checks if the event should happen on that day or not, the event was being added to the periodicEvents list regardless of if it occurred or not. This has now been fixed.

![image](https://cloud.githubusercontent.com/assets/22303564/24530719/d70a0be8-1581-11e7-9f8c-c74f3dcdc7b6.png)

**Comment by Light-Of-Darkness** [comment]
![image](https://cloud.githubusercontent.com/assets/22303564/24532825/6c231b34-1591-11e7-9a5d-d65327ef438d.png)

**Comment by Light-Of-Darkness** [comment]
The error was that in the non-daily periodic scheduling code, it would use the trigger of the event to help set a trigger for each day that the event should happen. However, instead of creating a duplicate TimeAndDate object, it ended up changing the trigger day Array that the event in the list was referencing.
