### ISSUE TITLE
Removing Periodic Event Name Repitition

### ISSUE THREAD

**Issue by JasonVanKerkhoven** [SYSC-3010-F5/AVA-SH#38]
Periodic events can be scheduled with the same name.
If an event exists with name "Alarm", an error should occur.
Instead, it is scheduled anyway

**Comment by Light-Of-Darkness** [comment]
Scheduler now rejects events with duplicate names.
MainServer will send an error packet to the schedule request if a periodic event name is repeated
![image](https://cloud.githubusercontent.com/assets/22303564/24530754/1c3eae62-1582-11e7-9e83-196f4e68d387.png)
